"use client"

import { MyContextProvider } from '@/utils/context'
import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body suppressHydrationWarning>
        <MyContextProvider>{children}</MyContextProvider>
      </body>
    </html>
  )
}
